Edureka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TasksManager/', include('TasksManager.urls')),
]

TasksManager/urls.py
from django.urls import path

from . import views

app_name = 'TasksManager'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    # path('', views.index, name='index'),
    #  path('<int:question_id>/', views.detail, name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

TasksManager/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

TasksManager/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Choice, Question
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'TasksManager/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        return the last five published questions.
        """
        # return Question.objects.order_by('pub_date')[:5]
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


def get_queryset():
    """
    Excludes any questions that aren't published yet
    """
    return Queston.objescts.filter(pub_date__lte=timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'TasksManager/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'TasksManager/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        # redisplay the question voting form
        return render(request, 'TasksManager/detail.html',
                      {'question': question, 'error_message': "you didn't select a choice.", })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # always return an HttpResponseRedirect after succesfully dealing
        # with POST data. this prevents data from being posted twice if a
        # user hits the back button twice
        return HttpResponseRedirect(reverse('TasksManager:results', args=(question.id,)))

    # return HttpResponse("you're voting on question %s." % question_id)

# # Create your views here.
# def index(request):
#     latest_question_list=Question.objects.order_by('pub_date')[:5]
#     # output = ', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(output)
#     template = loader.get_template('TasksManager/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))


# def detail(request, question_id):
#     # try:
#         # question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'TasksManager/detail.html', {'question' : question})
#     # return HttpResponse("you're looking at question %s." % question_id)


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'TasksManager/results.html', {'question':question})
#     # response = "you're looking at the response of question %s."
#     # return HttpResponse(response % question_id)

TasksManager/templates/TasksManager/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
    <h1>
        {{ question.question_text }}
    </h1>
    
    {% if error_message %}
    <p> <strong>
        {{ error_message }}
    </strong> </p>
    {% endif %}

    <form action="{% url 'TasksManager:vote' question.id%}" method="post">
        {% csrf_token %}
        {% for choice in  question.choice_set.all %}
        <input type="radio" name="choice" id="choice {{ forloop.counter }}"
               value=" {{ choice.id }}">
        <label for="choice {{ forloop.counter }}">
            {{ choice.choice_text }}
        </label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</body>
</html>

TasksManager/templates/TasksManager/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TasksManager</title>
</head>
<body>
{% if latest_question_list%}
    <ul>
        {% for question in latest_question_list%}
            <li><a href="/TasksManager/{{question.id}}/">
                {{ question.question_text }}
            </a></li>
            {% endfor %}
    </ul>
    {% else %}
        <p>no tasks available.</p>
    `{% endif %}
</body>
</html>

TasksManager/templates/TasksManager/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>results</title>
</head>
<body>
    <h1>
        {{ question.question_text }}
    </h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} --
        {{ choice.votes }} vote
        {{ choice.votes|pluralize }}
    </li>
    {% endfor %}
</ul>
    <a href="{% url 'TasksManager:detail' question.id %}">Vote again</a>
</body>
</html>